-- MySQL Script generated by MySQL Workbench
-- Tue Mar 28 23:16:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `id_match` INT NULL,
  PRIMARY KEY (`idticket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`achat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`achat` (
  `id_achat` INT NOT NULL AUTO_INCREMENT,
  `ticket_idticket` INT NOT NULL,
  `client_idclient` INT NOT NULL,
  PRIMARY KEY (`id_achat`, `ticket_idticket`, `client_idclient`),
  INDEX `fk_achat_ticket1_idx` (`ticket_idticket` ASC) VISIBLE,
  INDEX `fk_achat_client1_idx` (`client_idclient` ASC) VISIBLE,
  CONSTRAINT `fk_achat_ticket1`
    FOREIGN KEY (`ticket_idticket`)
    REFERENCES `mydb`.`ticket` (`idticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_achat_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prediction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prediction` (
  `id_prediction` INT NOT NULL AUTO_INCREMENT,
  `date_prediction` DATE NULL,
  `date_fin` DATE NULL,
  `client_idclient` INT NOT NULL,
  PRIMARY KEY (`id_prediction`, `client_idclient`),
  INDEX `fk_prediction_client1_idx` (`client_idclient` ASC) VISIBLE,
  CONSTRAINT `fk_prediction_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`match_predire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`match_predire` (
  `id_match_predire` INT NOT NULL AUTO_INCREMENT,
  `id_match` INT NULL,
  `score` VARCHAR(10) NULL,
  `prediction_id_prediction` INT NOT NULL,
  PRIMARY KEY (`id_match_predire`, `prediction_id_prediction`),
  INDEX `fk_match_predire_prediction_idx` (`prediction_id_prediction` ASC) VISIBLE,
  CONSTRAINT `fk_match_predire_prediction`
    FOREIGN KEY (`prediction_id_prediction`)
    REFERENCES `mydb`.`prediction` (`id_prediction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prix_par_place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prix_par_place` (
  `id_prix_par_place` INT NOT NULL,
  `place_type` VARCHAR(45) NULL,
  `prix` INT NULL,
  `nbr_place` INT NULL,
  `ticket_idticket` INT NOT NULL,
  PRIMARY KEY (`id_prix_par_place`, `ticket_idticket`),
  INDEX `fk_prix_par_place_ticket1_idx` (`ticket_idticket` ASC) VISIBLE,
  CONSTRAINT `fk_prix_par_place_ticket1`
    FOREIGN KEY (`ticket_idticket`)
    REFERENCES `mydb`.`ticket` (`idticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
